coverage_config_x86_64.json, src/backend.rs, src/vhost_kern/mod.rs, src/vhost_kern/vhost_binding.rs, src/vhost_kern/vsock.rs, src/vhost_user/message.rs
This is a misc patch series, which includes:
fixes one bug in vring address handling
upgrade to latest vm-memory
fix a typo
enlarge VHOST_USER_MAX_VRINGS to 0x8000
Fix of the previous PR #11
=> Prepare for supporting vhost-net

src/vhost_kern/mod.rs, src/vhost_kern/vhost_binding.rs, src/vhost_kern/vsock.rs, src/vhost_user/dummy_slave.rs, src/vhost_user/master.rs, src/vhost_user/master_req_handler.rs, src/vhost_user/message.rs, src/vhost_user/mod.rs, src/vhost_user/slave_fs_cache.rs, src/vhost_user/slave_req_handler.rs
Make `cargo clippy --all-features --all-targets` pass.
=> Fix clippy erros and warnings

coverage_config_x86_64.json, src/vhost_user/dummy_slave.rs, src/vhost_user/master.rs, src/vhost_user/message.rs, src/vhost_user/mod.rs, src/vhost_user/slave_req_handler.rs
This PR introduces the support for recently added message types `VHOST_USER_GET_MAX_MEM_SLOTS`, `VHOST_USER_ADD_MEM_REG` and `VHOST_USER_REM_MEM_REG`, coming from the latest `vhost-user` specification, and gated by the protocol feature `VHOST_USER_PROTOCOL_F_CONFIGURE_MEM_SLOTS`.
They are specifically designed for memory hotplug and memory hot-unplug. They are more efficient than using `VHOST_USER_SET_MEM_TABLE` as the backend does not need to remap all regions if a single region is added or removed.
For the particular case of adding new regions, `VHOST_USER_ADD_MEM_REG` overcome the limitation of 8 regions coming from `VHOST_USER_SET_MEM_TABLE`.
=> vhost_user: Add support for VHOST_USER_PROTOCOL_F_CONFIGURE_MEM_SLOTS

src/vhost_user/master.rs, src/vhost_user/message.rs
Modify the interpretation of the set and get config offset field to
match qemu. The wording in the vhost user spec is ambiguous, bet lets
defer to qemu's implementation so vhost based devices can be used with
qemu as a VMM. Fixes #29.
Signed-off-by: Dylan Reid <dgreid@chromium.org>
=> vhost_user: config offset matches qemu

src/lib.rs
Replace 'virtque' with 'virtqueue' and 'talbe' with 'table'.
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> Fix typos in the error messages

src/vhost_user/slave_req_handler.rs
We should allow to receive SET_VRING_ENABLE request with non-zero index even if
MQ protocol feature is disabled because some device can have multiple queues
without the MQ feature.
e.g. virtio-net means that it supports multiple pairs of tx/rx queues. So, the
slave must support at least one pair of queues regardless of whether MQ is
supported.
=> vhost_user: Fix check for SET_VRING_ENABLE

src/vhost_user/message.rs
Implementing From<...> provides the equivalent Into<..> automatically,
so this form is preferred.
Fixes the clippy from_over_into warning:
https://rust-lang.github.io/rust-clippy/master/index.html#from_over_into
Signed-off-by: Daniel Verkamp <dverkamp@chromium.org>
=> vhost_user: implement From instead of Into

src/vhost_user/master.rs
Based on the specification, one can call into
VHOST_USER_GET_PROTOCOL_FEATURES or VHOST_USER_SET_PROTOCOL_FEATURES
before VHOST_USER_SET_FEATURES.
The current code is wrong as it expects the VIRTIO features to be
already acknowledged at the time the protocol features are get/set.
Quote from the spec for both VHOST_USER_GET_PROTOCOL_FEATURES and
VHOST_USER_SET_PROTOCOL_FEATURES:
Slave that reported VHOST_USER_F_PROTOCOL_FEATURES must support this
message even before VHOST_USER_SET_FEATURES was called.
=> vhost_user: Fix wrong behavior for get/set protocol features

coverage_config_x86_64.json, src/vhost_user/master.rs
Introduce a new method set_flags() in order to let the caller define the
expected set of flags that should be applied to the header for the
following messages.
Fixes #40
=> vhost_user: Add header flags support

Cargo.toml, coverage_config_x86_64.json, src/vhost_user/dummy_slave.rs, src/vhost_user/master.rs, src/vhost_user/message.rs, src/vhost_user/mod.rs, src/vhost_user/slave_req_handler.rs
The inflight I/O tracking feature is useful for handling crashes and
disconnections from the backend. It allows the backend to rely on a
buffer that was shared earlier with the VMM to restore to the previous
state it was before the crash.
This feature depends on the availability of the protocol feature
VHOST_USER_PROTOCOL_F_INFLIGHT_SHMFD, and it implements both
VHOST_USER_GET_INFLIGHT_FD and VHOST_USER_SET_INFLIGHT_FD messages.
Fixes #43
=> vhost_user: Add Inflight I/O tracking support

src/vhost_user/slave_req_handler.rs
This fixes a problem I came across with QEMU and vhost.rs having slightly different ideas about when replies should be handled. We could probably do more to detect mismatches between the reply needed field and the negotiated state of the protocol.
=> Loosen reply ack

.buildkite/pipeline.yml, coverage_config_x86_64.json, src/vhost_user/message.rs
Allow enum names whose characters are all upper case such as `NOOP`.
This change is needed to uprev bump rust-vmm-ci's version at #46.
Signed-off-by: Keiichi Watanabe <keiichiw@chromium.org>
=> bump rust-vmm-ci with manual fixes

src/vhost_user/slave_req_handler.rs
A device process may already have a connected socket to the VMM, for
example by inheriting one end of a socketpair() created by the parent
process.  Add a method to create a SlaveReqHandler directly from a
connected socket.
=> Add SlaveReqHandler::from_stream

coverage_config_x86_64.json, src/vhost_user/connection.rs, src/vhost_user/dummy_slave.rs, src/vhost_user/master.rs, src/vhost_user/master_req_handler.rs, src/vhost_user/mod.rs, src/vhost_user/slave_fs_cache.rs, src/vhost_user/slave_req_handler.rs
Use `File` instead of `RawFd` in methods of `SlaveReqHandler` to handle
FDs' ownership easily.
Fixes #37.
Signed-off-by: Keiichi Watanabe <keiichiw@chromium.org>
=> vhost_user: Avoid passing around RawFd

coverage_config_x86_64.json, src/vhost_user/message.rs
These set of commits introduce the queue region and descriptor state structures needed to manage inflight I/O tracking.
=> Inflight io: Define queue regions for split and packed virtqueues

src/vhost_user/master.rs, src/vhost_user/mod.rs, src/vhost_user/slave_req_handler.rs
Move take_single_file() to mod.rs as it is used in both master feature
and slave feature so that we can build the master feature without the
slave feature.
Signed-off-by: Keiichi Watanabe <keiichiw@chromium.org>
=> vhost_user: Move utility function to mod.rs

coverage_config_x86_64.json, src/vhost_user/message.rs
The queue region and descriptor state structs introduced in the previous commits need to be public to be used by other crates.
=> Inflight I/O: Make structs and members public

coverage_config_x86_64.json, src/vhost_user/message.rs
fix warning, when compiling with 1.53.0
```
warning: reference to packed field is unaligned
--> src/vhost_user/message.rs:252:53
|
252 |         unsafe { std::mem::transmute_copy::<u32, R>(&self.request) }
|                                                     ^^^^^^^^^^^^^
|
= note: `#[warn(unaligned_references)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #82523 <https://github.com/rust-lang/rust/issues/82523>
= note: fields of packed structs are not properly aligned, and creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
```
Signed-off-by: wanglei <wllenyj@linux.alibaba.com>
=> fix `warning: reference to packed field is unaligned`

Cargo.toml
build(deps): update vm-memory requirement from 0.2.0 to 0.5.0
Updates the requirements on
[vm-memory](https://github.com/rust-vmm/vm-memory) to permit the latest
version.
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
=> update vm-memory requirement from 0.2.0 to 0.5.0

coverage_config_x86_64.json, src/backend.rs
It is helpful for the consumer of this crate to be able clone and copy
the VringConfigData structure, as well as being able to initialize it
only partially thanks to the Default trait.
=> Derive Default, Clone and Copy for VringConfigData

coverage_config_x86_64.json, src/backend.rs, src/vhost_kern/mod.rs, src/vhost_kern/vsock.rs, src/vhost_user/master.rs, src/vhost_user/message.rs, src/vhost_user/mod.rs
The SET_LOG_BASE implementation was incomplete as it didn't include the
ability to send the shared memory region information along with the file
descriptor.
This is required to perform proper dirty page logging with a vhost-user
device.
=> Fix set_log_base() implementation for vhost-user

src/vhost_user/message.rs
I think this might have been a remnant of the example in the fmt
documentation![1]
[1]: https://doc.rust-lang.org/stable/core/fmt/trait.Debug.html#examples
Signed-off-by: Alyssa Ross <hi@alyssa.is>
=> vhost_user: fix struct name in Debug impl

Cargo.toml
"Apache-2.0 or BSD-3-Clause" is not an valid license statement and is
rejected by cargo. So change it to "Apache-2.0 OR BSD-3-Clause".
Signed-off-by: Liu Jiang <gerry@linux.alibaba.com>
=> Fix an error in license statement

Cargo.toml, src/vhost_user/connection.rs, src/vhost_user/master.rs, src/vhost_user/message.rs
Converting arbitrary bytes into an arbitrary Rust value is unsafe.  For example, it's unsafe to create a `String` that isn't valid UTF-8.  But the various internal `recv*` functions didn't restrict their return types enough to enforce this invariant, making them unsafe without being properly marked.
To fix this, we tighten up the bounds of the functions to enforce that their return types are `ByteValued`, meaning that they can only be used to create types that are safe to initialize with arbitrary data such as might be received over a socket.
It's worth asking how these functions could have been unsafe in the first place, since they don't contain any unsafe blocks themselves. The answer is that the functions that `recv` into `iovec`s are also unsafe but not correctly marked.  I'm …
=> vhost_user: enforce ByteValued for recv-d structs

coverage_config_x86_64.json, src/vhost_user/connection.rs
Implement FromRawFd for Listener, using the underlying UnixListener
FromRawFd implementation.
This is useful when the listener socket is inherited as a file
descriptor from a parent (such as libvirt or a jailer).
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> vhost-user: Implement FromRawFd for Listener

coverage_config_x86_64.json, src/vhost_user/mod.rs
These error enums are required to handle various errors during
memfd_create, ftruncate and memfd sealing operations.
Signed-off-by: Harshavardhan Unnibhavi <harshanavkis@gmail.com>
=> Inflight I/O: Introduce new error enums

src/vhost_user/connection.rs, src/vhost_user/message.rs
`recv_with_fds` from vmm-sys-util was never safe, but was incorrectly not marked as safe.  Handle it safely in every function where we have enough information to know that calling it will be safe, and propogate the unsafe to any function where we don't.
Fortunately this is quite straightforward now all of the high-level methods have the guarantee that they're returning `ByteValued` types.
Signed-off-by: Alyssa Ross <hi@alyssa.is>
***
This change is necessitated by https://github.com/rust-vmm/vmm-sys-util/pull/135.  If it's merged before the vmm-sys-util dependency is updated to a version with that change, it will produce compiler warnings, so I've marked it as a draft until that PR is merged.
=> vhost_user: handle recv_with_fds being unsafe

Cargo.toml
crates.io does not allow publishing crates which have wildcards in
their dependencies. We had one for "serial_test", so replace the
wildcard pointing it to the current major/minor ("0.5").
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> Cargo: replace wildcard with 0.5 for serial_test

Cargo.toml
By relaxing the dependency to ">=0.6" this crate can be used in projects
using newer vm-memory without pulling in duplicates of the crate.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> build: Relax vm-memory dependency

LICENSE-BSD-3-Clause, src/vhost_kern/vdpa.rs
Add methods to restore Vdpa objects, so we could avoid marking all fields of VhostKernVdpa as pub.
=> Add method to restore Vdpa objects

src/vhost_kern/vdpa.rs
A wrong ioctl request was used in get_iova_range().
Unfortunately, there was no test, otherwise the ioctl would fail.
Let's fix this by using the right ioctl request.
We also add a test by checking the values we expect from
a vDPA-block simulator that returns [0, u64::MAX] range.
Fixes  #106
Reported-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
requirements:
test.
=> vhost_kern/vdpa: fix get_iova_range()

coverage_config_x86_64.json, src/vhost_user/dummy_slave.rs, src/vhost_user/master.rs, src/vhost_user/message.rs, src/vhost_user/mod.rs, src/vhost_user/slave_req_handler.rs
The InvalidOperation error type covers a wide range of error cases
which can be inscrutable when passed to the user. To help with this
we:
- add a textual reason field to the error message
- create InactiveFeature for use of un-neogitated features
- create InactiveOperation for use of un-negotiated protocol extensions
requirements:
test.
=> vhost_user: expand error messages for clarity

src/vdpa.rs, src/vhost_kern/vdpa.rs, src/vhost_kern/vhost_binding.rs, src/vhost_user/connection.rs
New ioctls have been recently introduced to interact with vDPA devices.
This patch is based on Linux kernel v6.0, adding the list of missing ioctls:
- VHOST_VDPA_GET_CONFIG_SIZE
- VHOST_VDPA_GET_VQS_COUNT
- VHOST_VDPA_GET_GROUP_NUM
- VHOST_VDPA_GET_AS_NUM
- VHOST_VDPA_GET_VRING_GROUP
- VHOST_VDPA_SET_GROUP_ASID
- VHOST_VDPA_SUSPEND
=> vhost_kern: vdpa: Add missing ioctls

crates/vhost/src/vhost_user/connection.rs, crates/vhost/src/vhost_user/mod.rs
It's important to be able to tell the difference between a client cleanly disconnecting (e.g. if a VM is shut down), and a partial message transmission.  To do this, introduce a new `Disconnected` error variant, to be used only when `recvmsg()` returns 0 when trying to receive a header, indicating the client disconnected after the last message.
Signed-off-by: Alyssa Ross <alyssa.ross@unikie.com>
requirements:
test.
=> vhost_user: add Error::Disconnected

crates/vhost/src/vhost_user/connection.rs, crates/vhost/src/vhost_user/master.rs, crates/vhost/src/vhost_user/message.rs, crates/vhost/src/vhost_user/slave_req_handler.rs
These functions were unsound because it was previously possible to trigger UB with them, but they were not marked as unsafe.
Struct padding in Rust is uninitialized.  So if a struct with padding had been passed to either of these functions as the body, it would have resulted in an uninitialized read, which is undefined behavior in Rust.
By restricting body values to be `ByteValued`, we avoid this, because types implementing `ByteValued` are guaranteed to be convertible to and from byte slices.
We then need to declare some types to be `ByteValued`, so that they can continue to be sent over the socket.
This is an internal-only API, and was never actually called incorrectly.
Signed-off-by: Alyssa Ross <alyssa.ross@unikie.com>
Before submitting your PR, please make sure you addressed the …
=> vhost_user: fix unsound send_message functions

crates/vhost/CHANGELOG.md, crates/vhost/src/vhost_user/connection.rs, crates/vhost/src/vhost_user/master.rs, crates/vhost/src/vhost_user/master_req_handler.rs, crates/vhost/src/vhost_user/message.rs, crates/vhost/src/vhost_user/mod.rs, crates/vhost/src/vhost_user/slave_req_handler.rs
Since `VhostUserMsgHeader` implements `ByteValued`, it is supposed to be safe to construct from any correctly-sized arbitrary byte array. But that means we can do this:
```rust
let bytes = b"\xFF\xFF\xFF\xFF\x00\x00\x00\x00\x00\x00\x00\x00";
let header = VhostUserMsgHeader::<MasterReq>::from_slice(bytes).unwrap();
header.get_code()
```
constructing an invalid `MasterReq`, using only functions that are marked as safe.  Constructing an invalid enum value is undefined behavior in Rust, so this API is unsound.  This wasn't considered by the safety comment in `VhostUserMsgHeader::get_code`, which only considered the safety of requests that were valid enum variants.
If the vhost-user frontend process sends a message that the backend doesn't recognise, that's exactly what will happen, so the UB …
=> vhost_user: fix unsoundness in VhostUserMsgHeader

crates/vhost-user-backend/src/backend.rs, crates/vhost-user-backend/src/handler.rs, crates/vhost-user-backend/tests/vhost-user-server.rs, crates/vhost/docs/vhost_architecture.drawio, crates/vhost/src/vhost_user/master_req_handler.rs, crates/vhost/src/vhost_user/mod.rs, crates/vhost/src/vhost_user/slave_req.rs, crates/vhost/src/vhost_user/slave_req_handler.rs
There are a lot of slave requests supported by vhost-user protocol, it isn't just about FS_MAP and FS_UNMAP. Rename the files and declarations to slave request specific names.
=> vhost_user: Slave requests aren't only FS specific

crates/vhost-user-backend/src/handler.rs
When the frontend sends the `GET_VRING_BASE` message, we should return the vring's last available index and stop the vring.  Commit https://github.com/rust-vmm/vhost/commit/17131359ebae207476d009a65b702f028b581622 reset the vring upon receiving `GET_VRING_BASE`, But to return the correct index we should not reset the queue before getting its value, otherwise we will always return 0.
Note:
Neither qemu[0] nor dpdk[1] reset the vring when receiving `GET_VRING_BASE`
[0] https://github.com/qemu/qemu/blob/792f77f376adef944f9a03e601f6ad90c2f891b2/subprojects/libvhost-user/libvhost-user.c#L1175
[1] https://github.com/DPDK/dpdk/blob/d03446724972d2a1bb645ce7f3e64f5ef0203d61/lib/vhost/vhost_user.c#L2133
=>  Fix return value of `GET_VRING_BASE` message

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/Cargo.toml, crates/vhost/CHANGELOG.md, crates/vhost/Cargo.toml
Update deps to sync with the main rust-vmm crates (vm-memory, virtio-queue and virtio-bindings) and set up the stage to cut a new release.
=> Update deps and set up the stage for vhost v0.7.0 and vub v0.9.0

crates/vhost/CHANGELOG.md, crates/vhost/src/vhost_kern/vdpa.rs
Unlike other vhost backends (e.g. vhost-net and vhost-vsock), vDPA
backends can not work with host virtual address (HVA), instead they
expect I/O virtual address (IOVA). The IOVA can be mapped 1:1 with
guest physical address (GPA) when no IOMMU is involved. This is why
the default implementation of `set_vring_addr()` from Trait
`VhostBackend` is no longer working with vDPA backends. To solve this
issue, this patch provides a custom `set_vring_addr()` implementation
for Trait `VhostKernVdpa`.
Fixes: #164
requirements:
test.
=> vhost: vdpa: Provide custom `set_vring_addr()` implementation

crates/vhost-user-backend/src/handler.rs
The spec specifies that on receiving `GET_VRING_BASE` the backend should stop the vring, but not that it must be reset. This is intended for `VHOST_USER_RESET_DEVICE`, also in this case the spec makes a difference between stopping and disabling the ring.
The spec also doesn't forbid to send `VHOST_USER_SET_VRING_ENABLE` to enable the vring after receiving `GET_VRING_BASE` or sending more `GET_VRING_BASE` messages, which would always respond 0. Moreover, qemu[0] doesn't reset the vring either.
[0] https://github.com/qemu/qemu/blob/792f77f376adef944f9a03e601f6ad90c2f891b2/subprojects/libvhost-user/libvhost-user.c#L1175
Note:
I just added blank lines around `self.vrings[index as usize].set_queue_ready(false);` because the first time I worked on this (#154) I didn't realize that the ring was …
=> get_vring_base should not reset the queue

crates/vhost/Cargo.toml
Since 4029089f ('vhost: Add support for Xen memory mappings') the feature backend-mmap of the vm-memory crate is no longer just a dev-dependency. Make it a formal dependency.
=> vhost: Always enable vm-memory/backend-mmap

crates/vhost/CHANGELOG.md
We experienced a small dependency issue with the `vm-memory` crate features, let's release this version to fix it.
=> vhost: Release v0.8.1

crates/vhost-user-backend/src/handler.rs, crates/vhost-user-backend/src/vring.rs
commit 958cdec2b8741af77b7f90214ec9c97040bf5a8a stopped GET_VRING_BASE from resetting the vring. This was required because when the VM is stopped/resumed the index will be 0 instead of the correct value.
However, after the guest driver changes, for instance, after reboot, the 'used' index should be 0. The bug fixed in that commit had the unintended side effect of setting the 'used' index to 0 after a driver change.
QEMU sets the 'used' index when receiving SET_VRING_ADDR, _probably_ to  make sure that the VQ is configured. Perhaps the appropriate place is  when receiving the first kick. A better solution would be to send the used index in SET_VRING_BASE, as is done when using packed VQs.
To keep compatibility with QEMU and just in case, any implementation expects the 'used' index to be …
=> vhost-user-backend: fetch 'used' index from guest

crates/vhost/CHANGELOG.md, crates/vhost/Cargo.toml, crates/vhost/src/vhost_kern/mod.rs, crates/vhost/src/vhost_kern/vdpa.rs
Update `CHANGLOG.md` for this release.
Unlike other vhost backends (e.g. vhost-net and vhost-vsock), vDPA
backends can not work with host virtual address (HVA), instead they
expect I/O virtual address (IOVA). The IOVA can be mapped 1:1 with
guest physical address (GPA) when no IOMMU is involved. This is why
the default implementation of `set_vring_addr()` from Trait
`VhostBackend` is no longer working with vDPA backends. To solve this
issue, this patch provides a custom `set_vring_addr()` implementation
for Trait `VhostKernVdpa`.
Fixes: #164
Signed-off-by: Bo Chen <chen.bo@intel.com>
`VhostBackend::set_vring_addr()` receives a vring config data which
contains the addresses of desc table, used ring and avail ring.
`VhostBackend::is_valid()` checks the addresses in the guest address space. …
=> Fix set_vring_addr issues and release vhost v0.6.1

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/Cargo.toml
Commit 8a4ba9d ("vhost-user-backend: fetch 'used' index from guest") fixes an issue introduced in v0.10.0 that affects all vhost-user backends like virtiofsd [1] or rust-vmm's vhost-device. I easily reproduced the problem with vhost-device-vsock as well: just restart the guest kernel and the device no longer works.
[1] https://gitlab.com/virtio-fs/virtiofsd/-/issues/120
=> vhost-user-backend: release v0.10.1

crates/vhost/src/vhost_user/message.rs
This code is currently unsound as it initializes an `&[u8]` that points to potential padding bytes.
https://github.com/rust-vmm/vhost/blob/6ca88e160a8d34be54a158cc1bc702e9250e97dd/crates/vhost/src/vhost_user/master.rs#L202
`repr(C)` would also work though it is brittle if the struct is change in the future, happy to switch over.
I also marked `VhostUserMsgValidator` as requiring `ByteValued` since `extract_request_body` assumes these types are POD.
https://github.com/rust-vmm/vhost/blob/6ca88e160a8d34be54a158cc1bc702e9250e97dd/crates/vhost/src/vhost_user/slave_req_handler.rs#L728
=> Safety fixes

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/src/backend.rs, crates/vhost-user-backend/src/lib.rs
We figured that all vhost-device daemons just ended up copying code from
each other. During an earlier attempt to solve that with a helper crate
for vhost-device [1], it was suggested to extend the vhost-user-backend
API directly. This way more people can benefit from this.
[1] https://github.com/rust-vmm/vhost-device/pull/362
requirements:
test.
=> Convenience function to listen + accept + wait + exit

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/src/backend.rs, crates/vhost-user-backend/src/event_loop.rs, crates/vhost-user-backend/tests/vhost-user-server.rs
The return value of VhostUserBackend::handle_event() is undocumented and difficult to interpret.
The current implementation used it to interrupt the event loop as it does when we receive an exit event.
All current implementations checked (rust-vmm/vhost-device, virtiofsd) return an error or always false, effectively not using this feature.
Since we already have a mechanism for breaking the event loop, we can avoid this ambiguous and redundant feature.
Closes #144
requirements:
test.
=> vhost-user-backend: remove return value from handle_event

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/src/backend.rs, crates/vhost-user-backend/src/event_loop.rs, crates/vhost-user-backend/src/handler.rs, crates/vhost-user-backend/src/lib.rs, crates/vhost-user-backend/tests/vhost-user-server.rs
In order to allow zero-cost exchanging of the concrete bitmap and vring
types, a lot of the generic code required using a tuple of
`<VringType, BitmapType>` for parameterizing the impl's. Once code is
also oblivious of the concrete backend (and a lot of code is), this
tuple turns into a triplet. Juggling these three single letter generic
parameters while making sure that all the type constraints (that are
also changing depending on the abstraction layer) does not feel very
ergonomic.
While one can argue that within this crate, this would be fine since
people probably know the internals, the design choice is leaking out
into every consumer of vhost-user-backend. Instead of just being able
to reference "some backend" one needs to copy a lot of boilerplate code
for also passing the other …
=> vhost-user-backend: simplify the use of generics

crates/vhost-user-backend/Cargo.toml, crates/vhost/Cargo.toml
Signed-off-by: Obei Sideg <obei.sideg@gmail.com>
Upgrade to 2021 edition
requirements:
test.
=> Upgrade to 2021 edition

Cargo.toml
After updating rust edition to 2021, cargo complains about the resolver:
warning: some crates are on edition 2021 which defaults to
`resolver = "2"`, but virtual workspaces default to
`resolver = "1"`
note: to keep the current resolver, specify
`workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify
`workspace.resolver = "2"` in the workspace root's manifest
Let's specify to use the edition 2021 resolver.
=> workspace: specify `workspace.resolver = "2"`

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/Cargo.toml, crates/vhost/CHANGELOG.md, crates/vhost/Cargo.toml
Preparation for a new release for both `vhost` and `vhost-user-backend`
I also run semver-checks:
```
$ cargo semver-checks check-release
Parsing vhost v0.9.0 (current)
Parsing vhost v0.8.1 (baseline)
Checking vhost v0.8.1 -> v0.9.0 (major change)
Completed [   0.000s] 0 checks; 0 passed, 48 unnecessary
Parsing vhost-user-backend v0.11.0 (current)
Parsing vhost-user-backend v0.10.1 (baseline)
Checking vhost-user-backend v0.10.1 -> v0.11.0 (major change)
Completed [   0.000s] 0 checks; 0 passed, 48 unnecessary
```
requirements:
test.
=> New releases: vhost v0.9.0 and vhost-user-backend v0.11.0

.github/dependabot.yml
This was tested on vhost-device successfully [1]. Lets enable it here!
[1] https://github.com/rust-vmm/vhost-device/commit/072fadaaba527133c3466cac90a8c5dd386b1f9e
Suggested-by: Patrick Roy <roypat@amazon.co.uk>
Suggested-by: Stefano Garzarella <sgarzare@redhat.com>
requirements:
- na All added/changed functionality has a corresponding unit/integration
test.
- na All added/changed public-facing functionality has entries in the "Upcoming 
- na Any newly added `unsafe` code is properly documented.
=> dependabot: enable update grouping

crates/vhost/src/vhost_user/message.rs
`NOOP` and `MAX_CMD` are not present in the vhost-user protocol, these are use only to verify that the value is correct before transmuting it to an `enum` variant.
This has two problems, firstly it exposes of non-standard values in a public interface, this internal implementation detail could be confusing, and secondly it assumes that the values are consecutive with no "holes" between them.
This results in having to define requests that are not actually supported, and error-prone, which can generate UB when transmuting.
Instead, it is better to implement `TryFrom<u32>` for enums that need to convert between variants and u32. This allows to remove the unsafe transmute.
=> Proper enum <-> value conversion

crates/vhost/src/vhost_user/message.rs
Let's remove commented vhost-user message definitions, some of the message definition are not supported and the other is duplicated (i.e., VhostUserLog is already defined).
I think we also need to remove the following back-end message types:
```rust
pub enum BackendReq {
...
/// Virtio-fs draft: map file content into the window.
FS_MAP = 6,
/// Virtio-fs draft: unmap file content from the window.
FS_UNMAP = 7,
/// Virtio-fs draft: sync file content.
FS_SYNC = 8,
/// Virtio-fs draft: perform a read/write from an fd directly to GPA.
FS_IO = 9,
...
}
```
These are not in the vhost-user standard, which in itself is confusing, but even conflict with values that are defined in the standard (see  [Back-end message types](https://qemu-project.gitlab.io/qemu/interop/vhost-user.html#id37)), such …
=> vhost_user: Remove commented code

crates/vhost/src/vhost_user/message.rs
Currently, some vhost-user-messages structs are defined with just `repr(packed)`, and also implement the `ByteValue` trait implying that they can be initialized safely from an array of bytes.
This is not safe, because the default memory representation does not guarantee that the fields will not be reordered.
Another issue that I didn't address in this PR is the struct:
```rust
/// Single memory region descriptor as payload for ADD_MEM_REG and REM_MEM_REG
/// requests.
#[repr(C)]
#[derive(Copy, Clone, Default)]
pub struct VhostUserInflight {
/// Size of the area to track inflight I/O.
pub mmap_size: u64,
/// Offset of this area from the start of the supplied file descriptor.
pub mmap_offset: u64,
/// Number of virtqueues.
pub num_queues: u16,
/// Size of virtqueues.
pub queue_size: u16,
} …
```
=> Fix structs incorrect memory layout

vhost-user-backend/src/handler.rs
VHostUserHandler::set_vring_base() lacks validation of the input parameter `index`, which is used for indexing an internal vector and could potentially lead to a Out-of-Bounds write resulting in a panic.
Closes #211
=> vhost-user-backend: check `index` in set_vring_base()

coverage_config_x86_64.json, vhost-user-backend/src/handler.rs
vhost-user-backend: take reference to `vring` once
In many places we access the `VhostUserHandler::vrings` array many
times and at the beginning of each function we check the index to
avoid OOB.
It happened that we forgot about this check (see #211), so let's
avoid this error-prone pattern by taking the reference to the vring
using `Vec::get()`, and avoiding multiple indexing.
Suggested-by: Erik Schilling <erik.schilling@linaro.org>
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>
=> vhost-user-backend: take reference to `vring` once

vhost-user-backend/Cargo.toml, vhost/Cargo.toml, vhost/src/vhost_kern/vdpa.rs
Hey everyone, I am propagating some dependency updates across the rust-vmm ecosystem. This one brings a fix for a security vulnerability behind feature-gated code not used by vhost (the with-serde feature), see [GHSA-875g-mfp6-g7f9](https://github.com/rust-vmm/vmm-sys-util/security/advisories/GHSA-875g-mfp6-g7f9).
requirements:
test.
=> Update vmm-sys-util to 0.12.1

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost/CHANGELOG.md, vhost/Cargo.toml, vhost/src/vhost_user/connection.rs, vhost/src/vhost_user/frontend.rs
This release only includes a dependency update, which is visible in the public API through `VhostBackend::set_vring_kick` and `VhostBackend::set_vring_call`.
requirements:
test.
=> chore: Prepare vhost 0.10.0 and vhost-user-backend 0.12.0 releases

vhost-user-backend/src/handler.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/mod.rs
Let's support up to 509 memslots, just like vhost in the kernel usually does. This is required to properly support memory hotplug, either using multyiple DIMMs (ACPI supports up to 256) or using virtio-mem.
The 509 used to be the KVM limit, it supported 512, but 3 were used for internal purposes. Currently, KVM supports more than 512, but it usually doesn't make use of more than ~260 (i.e., 256 DIMMs + boot memory), except when other memory devices like PCI devices with BARs are used. So, 509 seems to work well for vhost in the kernel.
Details can be found in the QEMU change that made virtio-mem consume up to 256 memslots accross all virtio-mem devices. [1]
509 memslots implies 509 VMAs/mappings in the worst case (even though, in practice with virtio-mem we won't be seeing more than ~260 …
=> vhost-user-backend: bump up MAX_MEM_SLOTS to 509

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml
Before this release, vhost-user devices using this crate were limited to 32 memslots. This does not support well the integration with virtio-mem.
For more details: https://issues.redhat.com/browse/RHEL-15317
requirements:
test.
=> vhost-user-backend: prepare v0.13.0 release

vhost-user-backend/src/handler.rs
This was introduced in 7f326dd314fdea0f98a19fa039c630b50deaec0b, but
doesn't work with qemu versions < 7.2. SET_FEATURES is received before 
SET_VRING_KICK, we will enable the vrings in set_features() and disabled
them later in set_vring_kick().
Currently, the libvhostuser in qemu disables the vring upon receiving
RESET_OWNER, but that message is currently deprecated. There is not a 
sane place to disable the vring, since according to the spec we can only
do that upon receiving RESET_OWNER (deprecated), RESET_DEVICE (currently
not supported in this crate), and SET_VRING_ENABLE.
The current state of the vhost-user spec is a mess, we need a more
formal spec that just a wall of english.
It also, fixes an incorrect comment.
=> vhost-user-backend: Fix SET_VRING_KICK should not disable the vring

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml
Fix a regression introduced by commit 7f326dd ("vhost-user-backend: SET_FEATURES must not disable any ring").
SemVer compatibility checked:
```
$ cargo semver-checks check-release -p vhost-user-backend
Parsing vhost-user-backend v0.13.1 (current)
Parsing vhost-user-backend v0.13.0 (baseline, cached)
Checking vhost-user-backend v0.13.0 -> v0.13.1 (minor change)
Completed [   0.030s] 42 checks; 42 passed, 6 unnecessary
```
requirements:
test.
=> vhost-user-backend: prepare v0.13.1 release

.buildkite/README.md, .buildkite/rust-vmm-ci-tests.json
This is based on `rust-vmm-ci/.buildkite/test_description.json`.
We can't run rust-vmm-ci tests because they enable all the features with
`--all-features` and our crates have features that may not be compatible with
others (e.g. `xen`). Waiting to solve this problem in rust-vmm-ci (see
https://github.com/rust-vmm/rust-vmm-ci/issues/152), we use a custom
pipeline based on that but that does not use `--all-features`.
requirements:
test.
=> tests: add rust-vmm-ci-tests.json pipeline

coverage_config_x86_64.json, vhost-user-backend/src/backend.rs, vhost-user-backend/src/handler.rs, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/message.rs
A new set of messages have been introduced in the vhost-user protocol to support the migration of devices with back-end's internal state[0].
These are the additions to the protocol:
- New vhost-user protocol feature `VHOST_USER_PROTOCOL_F_DEVICE_STATE`
- `SET_DEVICE_STATE_FD` function: Front-end and back-end negotiate a file
descriptor over which to transfer the state. It also includes
establishing the direction of transfer and migration phase.
- `CHECK_DEVICE_STATE`: After the state has been transferred through the
file descriptor, the front-end invokes this function to verify
success.  There is no in-band way (through the file descriptor) to
indicate failure, so we need to check explicitly.
[0] https://github.com/qemu/qemu/commit/019233096c03b826e0e677115b6e3c550a54a48d
This code is …
=> Add back-end's internal state migration support

.buildkite/rust-vmm-ci-tests.json, coverage_config_x86_64.json, vhost-user-backend/Cargo.toml, vhost-user-backend/README.md, vhost-user-backend/src/handler.rs, vhost-user-backend/src/lib.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/Cargo.toml, vhost/README.md, vhost/src/lib.rs, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/frontend.rs, vhost/src/vhost_user/message.rs
Added ability to use `VHOST_USER_POSTCOPY_ADVISE`, `VHOST_USER_POSTCOPY_LISTEN` and `VHOST_USER_POSTCOPY_END` messages. This includes sending them from the frontend and processing them on the backend.
The `POSTCOPY` messages are only usable when
`VHOST_USER_PROTOCOL_F_PAGEFAULT` feature is negotiated.
Messages and their descriptions are:
- `VHOST_USER_POSTCOPY_ADVISE`:
When the front-end sends this message to the backend,
the back-end must open a userfaultfd for later use
and send it's fd to the front-end.
- `VHOST_USER_POSTCOPY_LISTEN`
When the back-end receives this message it must ensure
that shared memory is registered with userfaultfd to
cause faulting of non-present pages.
This is always sent sometime after a `VHOST_USER_POSTCOPY_ADVISE`.
- `VHOST_USER_POSTCOPY_END`
When the …
=> Adding POSTCOPY support

vhost-user-backend/CHANGELOG.md, vhost-user-backend/src/bitmap.rs, vhost-user-backend/src/handler.rs, vhost-user-backend/src/lib.rs, vhost/CHANGELOG.md, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/message.rs
The vhost user protocol supports live migration, and during live migration, the vhost-user frontend needs to track the modifications the vhost-user backend makes to the memory mapped regions, marking the dirty pages in a log (i.e., a bitmap).
If the backend has the VHOST_USER_PROTOCOL_F_LOG_SHMFD protocol feature, it will receive the VHOST_USER_SET_LOG_BASE message with a file descriptor of the dirty-pages log memory region. This log covers all known guest addresses, and must be manipulated atomically.
For further info please see
https://qemu-project.gitlab.io/qemu/interop/vhost-user.html#migration
This PR adds support for creating an atomic-memory-mapped bitmap, and being able to replace it in runtime. The vhost user protocol does not specify whether the previous bitmap is still active …
=> Add replaceable-mmapped bitmap support

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost/CHANGELOG.md, vhost/Cargo.toml
This release adds support for live migration, adding dirty pages tracking and initial postcopy support.
Closes #234
=> Release vhost-v0.11.0 and vhost-user-backend-v0.14.0

vhost-user-backend/CHANGELOG.md, vhost-user-backend/src/handler.rs
A frontend can skip the call to set_vring_base, assuming the ring will be initialized at 0.  If that frontend acknowledge EVENT_IDX vring and VhostUserHandler backend will never know they need to use event idx.
Move the features configuration of the vring and the backend to set_features method.
---
I'm not 100% sure we should remove from set_vring_base.  QEMU history shows SET_FEATURES and SET_VRING_BASE were added by the same patch, so I guess there are no frontends not sending SET_FEATURES.  Even if it is using a transitional device.
At least, it is way more unlikely than frontends skipping SET_VRING_BASE.
Not adding unit/integration test. A guide on how to do that would be useful. Due to that, marking as a draft.
=> vhost-user-backend: set event_idx boolean at set_features

vhost-user-backend/CHANGELOG.md, vhost-user-backend/src/handler.rs, vhost/CHANGELOG.md, vhost/Cargo.toml, vhost/src/vhost_user/backend_req.rs, vhost/src/vhost_user/frontend_req_handler.rs, vhost/src/vhost_user/message.rs
Add `SHARED_OBJECT_*` vhost-user message IDs to align with standard at
https://qemu-project.gitlab.io/qemu/interop/vhost-user.html
Move `FS_*` type IDs to avoid current and future collisions.
requirements:
test.
=> Add shared object

coverage_config_x86_64.json, vhost/CHANGELOG.md, vhost/src/vhost_user/backend_req.rs, vhost/src/vhost_user/frontend_req_handler.rs, vhost/src/vhost_user/message.rs
Since these non-standard backend request
message types are confirmed not to be used
anymore, let's just remove them.
```
pub enum BackendReq {
...
/// Virtio-fs draft: map file content into the window.
FS_MAP = 100,
/// Virtio-fs draft: unmap file content from the window.
FS_UNMAP = 1001,
/// Virtio-fs draft: sync file content.
FS_SYNC = 1002,
/// Virtio-fs draft: perform a read/write from an fd directly to GPA.
FS_IO = 1003,
...
}
```
Closes: #213
requirements:
test.
=> vhost_user: Remove support for FS_* requests

vhost/CHANGELOG.md, vhost/src/vhost_user/frontend.rs
virtiofsd 1.11.0 added support for VHOST_USER_PROTOCOL_F_DEVICE_STATE. Upgrading virtiofsd meant that the latest released version of Cloud Hypervisor (39.0) was no longer able to communicate with it, because rather than just ignoring the unsupported feature, it got an unrecoverable "invalid message" error.  This demonstrates that it's better for frontends to just ignore offers of unsupported features. If the backend requires some feature, it'll get a chance to know that when we send VHOST_USER_SET_PROTOCOL_FEATURES anyway.
requirements:
test.
Release" section of CHANGELOG.md (if no such …
=> vhost_user: ignore unknown features from backend

.buildkite/rust-vmm-ci-tests.json, vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost-user-backend/src/backend.rs, vhost-user-backend/src/handler.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/CHANGELOG.md, vhost/Cargo.toml, vhost/src/vhost_user/backend.rs, vhost/src/vhost_user/backend_req.rs, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/connection.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/frontend.rs, vhost/src/vhost_user/frontend_req_handler.rs, vhost/src/vhost_user/gpu_backend_req.rs, vhost/src/vhost_user/gpu_message.rs, vhost/src/vhost_user/message.rs, vhost/src/vhost_user/mod.rs
Me and @dorindabassey have been working on this PR, which adds support for the QEMU's [vhost-user-gpu protocol](https://www.qemu.org/docs/master/interop/vhost-user-gpu.html). 
This is a protocol for sending messeges from backend to the fronted, it is needed to implement display output in QEMU to implement a [vhost-user-gpu device](https://github.com/rust-vmm/vhost-device/issues/598).
See issue #236 
This feature is very similar to the `SET_BACKEND_REQ_FD`, so it is implemented in a similar way.
Support is only added for sending these vhost messages from backend to frontend. Support for handling this protocol on frontend is not implemented.
The protocol is very similar to the normal vhost protocol, but the valid header flags of the `VhostUserMsgHeader` and the newly introduced …
=> Add support for VHOST_USER_GPU_SET_SOCKET

vhost/src/vhost_user/connection.rs
This is a small PR to fix a bug in test `create_listener_from_raw_fd()`, to make sure a file descriptor is not closed after ownership is passed to another object.
This actually causes a crash when running `cargo test` using the latest Rust toolchain version `1.80`, with the error message:
```
fatal runtime error: IO Safety violation: owned file descriptor already closed
```
requirements:
test.
=> Fix bug in unsafe code of test create_listener_from_raw_fd()

vhost-user-backend/src/handler.rs
It can be useful to debug the various address mappings sent to a vhost user device backend. impl Debug for both the postcopy and non-postcopy versions of AddrMapping.
=> vhost-user-backend: impl Debug for AddrMapping

.buildkite/rust-vmm-ci-tests.json, vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost-user-backend/src/backend.rs, vhost-user-backend/src/handler.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/CHANGELOG.md, vhost/Cargo.toml, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/mod.rs
make `set_gpu_socket` method a default implementation and remove conditional compilation because cargo feature unification already defeats the purpose of the `gpu-socket` feature flag.
Fixes #265 
requirements:
test.
=> Fix feature unification issues with gpu-socket feature

vhost-user-backend/CHANGELOG.md, vhost-user-backend/src/backend.rs, vhost-user-backend/src/handler.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/CHANGELOG.md, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/frontend.rs
The main point of this PR is to add vhost-user back-end support for the `RESET_DEVICE` message. This message is handled by disabling all vrings and resetting the device state (as per [the specification, look for `VHOST_USER_RESET_DEVICE`](https://qemu-project.gitlab.io/qemu/interop/vhost-user.html#front-end-message-types)). This includes a new `VhostUserBackend::reset_device()` method that back-end implementations may provide to clear additional internal state they keep.
virtiofsd needs this so a hard reset cannot be used to inherit state from a prior user ([virtiofsd issue #167](https://gitlab.com/virtio-fs/virtiofsd/-/issues/167) – note that the issue describes a bug in qemu that would prevent it from sending `RESET_DEVICE`, which has [since been …
=> Add suport for VHOST_USER_RESET_DEVICE

vhost-user-backend/CHANGELOG.md, vhost/CHANGELOG.md
These versions got yanked because the `gpu_socket` feature introduced
in this release was causing problems (see [#265](https://github.com/rust-vmm/vhost/issues/265)).
Starting with the next versions, the `gpu_socket` feature was removed.
requirements:
test.
=> Yank vhost v0.12.0 and vhost-user-backend v0.16.0

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost/CHANGELOG.md, vhost/Cargo.toml
This release adds support for `VHOST_USER_RESET_DEVICE` and updates vm-memory to 0.16.0 and virtio-queue to 0.13.0.
Closes #275 
requirements:
test.
=> Prepare vhost v0.13.0 and vhost-user-backend v0.17.0 releases

vhost-user-backend/CHANGELOG.md, vhost/CHANGELOG.md
Every time I do a release I notice this difference between
changelogs in this workspace, so let's try to uniform them by using
the form used in vhost-user-backend: without square brackets in the
title of the release and the `v` as prefix (v0.0.0).
Also fixed some difference in how we link PRs, let's follow the
most used way: [[#000]](url)
requirements:
test.
=> CHANGELOGs: uniform and fix some inconsistencies

vhost/CHANGELOG.md, vhost/src/vhost_user/backend_req_handler.rs
In BackendReqHandler::POSTCOPY_ADVISE, refactor the reply header
initialization for clarity and reuse.
requirements:
test.
=> vhost: Refactor reply header initialization in POSTCOPY_ADVISE

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost-user-backend/src/backend.rs, vhost-user-backend/src/handler.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/CHANGELOG.md, vhost/src/vhost_user/backend_req_handler.rs, vhost/src/vhost_user/dummy_backend.rs, vhost/src/vhost_user/frontend.rs, vhost/src/vhost_user/mod.rs
This PR adds support for the VHOST_USER_GET_SHARED_OBJECT message as described in the QEMU [specification](https://qemu-project.gitlab.io/qemu/interop/vhost-user.html) 
When the VHOST_USER_GET_SHARED_OBJECT is triggered from a vhost device, this message is expected to return a fd with reference to the resources specified by the uuid. This message can be used if a vhost device export resources (SHARED_OBJECT_ADD), and the UUID for that resource is found in the exporters cache.  This message allows forwarding of the fd to another vhost device in form of SHARED_OBJECT_LOOKUP message which imports the resources.
requirements:
summary and max 75 …
=> Add VHOST_USER_SHARED_OBJECT support

vhost/src/vhost_kern/mod.rs
Our CI is being upgraded to Rust 1.85 and this will produce new warnings from clippy like this one:
```
error: this `map_or` can be simplified
--> vhost/src/vhost_kern/mod.rs:79:12
|
79 |           if GuestAddress(config_data.desc_table_addr)
|  ____________^
80 | |             .checked_add(desc_table_size)
81 | |             .map_or(true, |v| !m.address_in_range(v))
| |_____________________________________________________^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
= note: `-D clippy::unnecessary-map-or` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::unnecessary_map_or)]`
help: use is_none_or instead
|
79 ~         if GuestAddress(config_data.desc_table_addr)
80 + …
```
=> vhost: fix clippy warnings on Rust 1.85

vhost/src/vhost_user/gpu_backend_req.rs, vhost/src/vhost_user/gpu_message.rs
This resolves a rustdoc warning, and makes the links appear as links in the rendered documentation.
requirements:
test.
=> vhost_user: format links in docs correctly

vhost-user-backend/src/handler.rs
For use in QEMU, I would like GuestMemoryRegion to return a BitmapSlice instead of a &Bitmap ([rust-vmm/vm-memory#324](https://github.com/rust-vmm/vm-memory/pull/324)).  This adds some flexibility that QEMU needs in order to support a single global dirty bitmap that is sliced by the various GuestMemoryRegions.
However, this removes access to the BitmapReplace trait, because it is of course not possible to replace a slice of the bitmap only.  Fortunately, vhost is built around the GM<> type alias, which has a pluggable bitmap type but hardcodes the backend:
type GM<B> = GuestMemoryAtomic<GuestMemoryMmap<B>>;
and therefore `region` is known to be a GuestRegionMmap.  Adding a single dereference of the GuestRegionMmap returns the MmapRegion to which the bitmap is attached, thus calling …
=> set_log_base: use MmapRegion::bitmap() directly

vhost-user-backend/tests/vhost-user-server.rs, vhost/CHANGELOG.md, vhost/src/vhost_user/backend_req_handler.rs
I observed hangs in the following situation when using Cloud Hypervisor with virtiofsd:
1. Start virtiofsd
2. Start Cloud Hypervisor instance 1, connected to virtiofsd.
3. Start Cloud Hypervisor instance 2, waiting for migration.
4. Migrate VM from Cloud Hypervisor instance 1 to 2.
5. Start virtiofsd again.
The hangs happened because Cloud Hypervisor remembered, as part of the migration data, which vhost-user protocol features the backend for its fs device supported.  Instance 2 therefore never sent `GET_PROTOCOL_FEATURES` to the second invocation of virtiofsd.  This should work, but it didn't, because `update_reply_ack_flag()` checked whether self.protocol_features contained `GET_PROTOCOL_FEATURES`, but `self.protocol_features` is only filled in when `GET_PROTOCOL_FEATURES` is called. …
=> vhost_user: fix replies without GET_PROTOCOL_FEATURES

Cargo.toml, vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml
Bump virtio-queue from v0.14.0 to v0.15.0
Bump virtio-bindings from v0.2.1 to v0.2.5
Also prepare for a new release of the crate.
requirements:
test.
=> Update virtio-queue and virtio-bindings to latest version and prepare for new release

vhost-user-backend/src/bitmap.rs, vhost-user-backend/src/vring.rs, vhost/src/vhost_user/backend_req.rs, vhost/src/vhost_user/gpu_backend_req.rs
There is a new warning reported by nightly compiler about mismatched lifetime syntaxes. Add the missing lifetime where ever required.
requirements:
test.
=> vhost: Fix clippy warning from nightly compiler

Cargo.toml, vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml
Bump virtio-queue from v0.15.0 to v0.16.0
Bump virtio-bindings from v0.2.5 to v0.2.6
Also prepare for the new release of vhost-user-backend crate
requirements:
test.
=> Update virtio-bindings crate and prepare for the new release of vhost-user-backend

vhost/CHANGELOG.md, vhost/src/vhost_user/connection.rs
It was already possible to do this as follows:
```rust
unsafe { Listener::from_raw_fd(listener.into_raw_fd()) }
```
This just factors the `From` implementation out of the `FromRawFd` implementation so it's possible to do the conversion without an unnecessary `unsafe` in application code.
requirements:
test. <ins>(Covered by the existing test for `FromRawFd`.)</ins>
=> vhost: `impl From<UnixListener> for Listener`

vhost-user-backend/src/vring.rs
rust 1.89 made the "mismatched lifetime syntaxes" lint to show a warning by default:
https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint
Add a placeholder lifetime to `vhost_user_backend::vring::VringStateMutGuard` to be explicit.
=> Fix "mismatched lifetime syntaxes" warning

Cargo.toml, vhost-user-backend/CHANGELOG.md, vhost-user-backend/src/backend.rs, vhost-user-backend/src/event_loop.rs, vhost-user-backend/src/lib.rs, vhost-user-backend/src/vring.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/src/vhost_user/connection.rs
Eventfd is Linux-specific. To support more platforms, we replace it with
the EventNotifier/EventConsumer abstractions.
EventSender and EventReceiver are wrappers that encapsulate eventfd functionality
Use pipefd to replace eventfd in the test.
requirements:
- [ x ] All commits in this PR have Signed-Off-By trailers (with
- [ x ] All added/changed functionality has a corresponding unit/integration
test.
- [ x ] All added/changed public-facing functionality has entries in the "Upcoming 
- [ x ] Any newly added …
=> Replace Eventfd with EventNotifier/EventConsumer

vhost-user-backend/CHANGELOG.md, vhost-user-backend/src/lib.rs, vhost-user-backend/tests/vhost-user-server.rs, vhost/CHANGELOG.md, vhost/src/vhost_user/backend.rs, vhost/src/vhost_user/mod.rs
The vhost-device devices all call `VhostUserDaemon::serve` in a loop, to handle reconnections.  This is not ideal, because a new listener is created each loop iteration, which means that each time, the old socket is unlinked and a new one is created.  This means that there's a potential race where a frontend attempts to connect to the backend before the new socket is created.
A more robust way to achieve this would be to have the devices create their own listeners, and pass the same one to `VhostUserDaemon::start` on each loop iteration, instead of letting `VhostUserDaemon::serve` create it repeatedly.  This was not previously possible though, because `VhostUserDaemon::start` consumed the listener, even though it didn't need to.
Because it's now possible to call `VhostUserDaemon::start` …
=> vhost_user: don't take ownership of `Listener`
