rust-vmm/vhost

src/vhost_user/connection.rs, src/vhost_user/master.rs, src/vhost_user/mod.rs
Instead of taking a `&str` for the path of the sockets, take
`AsRef<Path>`. This way users can pass `PathBuf`, `Path`, `String`, or
`&str`.
Signed-off-by: Dylan Reid <dgreid@chromium.org>
=> Allow using Path/PathBuf for initialization

.buildkite/pipeline.yml
=> Add custom pipeline yaml for wider clippy coverage

src/vhost_user/master.rs, src/vhost_user/slave_req_handler.rs
Except the list of commands from which we can expect a reply, all the
other commands should be able to reply with an acknowledgment if being
asked for.
For the commands such as SET_PROTOCOL_FEATURES, which usually happens
before the protocol features negotiation is complete, we should also be
able to reply with an ACK if needed. Indeed, the protocol features
negotiation could have happened earlier, which means we might expect a
reply ACK from GET_FEATURES command if this happens later on.
=> vhost_user: Fix NEED_REPLY for all messages

src/vhost_user/message.rs
Signed-off-by: Harshavardhan Unnibhavi <harshanavkis@gmail.com>
=> Inflight I/O: Make struct members public

CHANGELOG.md, Cargo.toml
Update version in Cargo.toml and add info about v0.2.0 to CHANGELOG.md
Signed-off-by: Sergio Lopez <slp@redhat.com>
=> Prepare for release v0.2.0

CHANGELOG.md, Cargo.toml, coverage_config_x86_64.json, src/vhost_user/dummy_slave.rs, src/vhost_user/mod.rs, src/vhost_user/slave_req_handler.rs
1) Fix a bug in SlaveReqHandler::set_config()
2) Generate documentation for doc.rs with all features enabled.
=> Prepare for publishing v0.3.0

coverage_config_x86_64.json, src/backend.rs, src/vhost_kern/net.rs, src/vhost_kern/vdpa.rs, src/vhost_kern/vsock.rs, src/vhost_user/master.rs, src/vhost_user/message.rs, src/vhost_user/mod.rs, src/vhost_user/slave_fs_cache.rs, src/vhost_user/slave_req_handler.rs
This PR includes the original one from dependabot #101 
It fixes clippy warnings and test coverage due to updated Rust version.
=> Fix warnings and update test coverage

src/vhost_kern/vdpa.rs
Since vDPA could be dealing with IOVAs corresponding to GVAs, it
wouldn't make sense to go through the validation of the descriptor
table address, available ring address and used ring address against
the guest memory representation we have access to.
For this reason, we override the default implementation of the valid()
method from the VhostKernBackend trait, to provide a simpler
implementation.
requirements:
test.
=> vhost_kern: vdpa: Override the implementation of valid()

Cargo.toml
Use caret requirements for dependencies.
Fixes: rust-vmm/community#131
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
requirements:
test.
=> update dependency requirements

CHANGELOG.md, Cargo.toml
See CHANGELOG.md file for details.
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
requirements:
test.
=> release 0.5.0

crates/vhost-user-backend/Cargo.toml, crates/vhost/Cargo.toml
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> {vhost, vhost-user-backend}: Bulk update rust-vmm dependencies

crates/vhost-user-backend/CHANGELOG.md, crates/vhost-user-backend/Cargo.toml, crates/vhost/CHANGELOG.md, crates/vhost/Cargo.toml
See https://github.com/rust-vmm/community/issues/136
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
requirements:
test.
=> Release vhost v0.6.0 and vhost-user-backend v0.8.0

crates/vhost-user-backend/src/handler.rs
There is a better error to use when we haven't negotiated a VirtIO feature. Lets use it.
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
=> vhost-user-backend: use InactiveFeature error

crates/vhost/src/vhost_kern/mod.rs
`VhostBackend::set_vring_addr()` receives a vring config data which
contains the addresses of desc table, used ring and avail ring.
`VhostBackend::is_valid()` checks the addresses in the guest address space.
`VHOST_SET_VRING_ADDR` uses the addresses in the host address space.
However, the method doesn't convert those addresses.
To address this issue, the addresses passed by the config are checked in
the guest address space. Then, they are converted by
`VringConfigData::to_vhost_vring_addr()` into the host address space to
setup the vring on the kernel.
Signed-off-by: Xuewei Niu <niuxuewei.nxw@antgroup.com>
=> Fix set_vring_addr issues

crates/vhost-user-backend/src/event_loop.rs
No need to repeat the struct definition here. The only purpose is to register an event_fd at epoll if one exists.
requirements:
test.
=> vhost-user-backend: de-duplicate match branches

crates/vhost/CHANGELOG.md, crates/vhost/src/backend.rs
=> Vhost user fix

crates/vhost/src/vhost_user/master.rs
use into() to convert bool into integer
rather than 'if enable { 1 } else { 0 }'
requirements:
test.
=> vhost: Fix clippy warnings.

CODEOWNERS
@stefano-garzarella asked me whether I would be willing to help with reviews here.
While my availability will probably be a lot worse starting with next year, I should still be able to do some reviews or ocassional releases.
requirements:
- `na` All added/changed functionality has a corresponding unit/integration
test.
- `na` All added/changed public-facing functionality has entries in the "Upcoming 
- `na` Any newly added `unsafe` code is properly documented.
=> CODEOWNERS: add myself

crates/vhost-user-backend/src/handler.rs
The vhost-user spec has been updated to clarify enabling and disabling vrings. The current spec states that upon receiving a `VHOST_USER_SET_FEATURES` message from the front-end without `VHOST_USER_F_PROTOCOL_FEATURES` set, the back-end must enable all rings immediately. Also, while processing the rings (whether they are enabled or not), the back-end must support changing some configuration aspects on the fly.
However, the vhost-user-backend implementation will disable all vring whenever this feature is negotiated, which means that every `VHOST_USER_SET_FEATURES` message could unintentionally halt the device.
This is an incorrect interpretation of the spec, and is problematic because the `VHOST_F_LOG_ALL` feature is also set or cleared by `VHOST_USER_SET_FEATURES`, which happens during …
=> vhost-user-backend: SET_FEATURES must not disable any ring

vhost/README.md
vhost_architecture.png link is broken.
requirements:
test.
=> Fix broken link of vhost docs

vhost-user-backend/Cargo.toml, vhost/Cargo.toml
=> builds: bump vm-memory and virtio-queue

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost/CHANGELOG.md, vhost/Cargo.toml
=> Release vhost-v0.12.0 and vhost-user-backend-v0.16.0 

Cargo.toml, vhost-user-backend/Cargo.toml, vhost/Cargo.toml
- build: Centralize rust-vmm crates to workspace
requirements:
test.
=> build: Centralize rust-vmm crates to workspace

vhost-user-backend/CHANGELOG.md, vhost-user-backend/Cargo.toml, vhost/CHANGELOG.md, vhost/Cargo.toml
Remove the gpu-socket feature just introduced, since it doesn't work well with cargo feature unification.
requirements:
test.
=> vhost v0.12.1 and vhost-user-backend v0.16.1 release

vhost/src/lib.rs
=> vhost: fix markdown formatting of docs heading

vhost/README.md
The link to vhost-user protocol is 404, replace it with the latest one.
requirements:
test.
=> vhost: Fix broken link in vhost/README.md

CODEOWNERS
Help out with PR reviews and various maintenance tasks.
requirements:
test.
=> CODEOWNERS: add myself as reviewer
